#
# DHCP Server Configuration file.
#   see /usr/share/doc/dhcp-server/dhcpd.conf.example
#   see dhcpd.conf(5) man page
#
authoritative;

default-lease-time 600;
max-lease-time 7200;


option domain-name "lab.local";
option domain-name-server 192.168.99.225;

subnet 192.168.99.0 netmask 255.255.255.0 {

	range 192.168.99.100 192.168.99.200;
	
	option routers 192.168.99.1;

	#PXE server
	next-server 192.168.99.235;
	
	#UEFI PXE BOOT CONFIG
	class "pxeclients" {
		match if substring(option vendor-class-identifier, 0, 9) = "PXEClient";
	}

	if option arch = 00:07 {
		filename "EFI/BOOT/grubx64.efi";
	}

	elseif option arch = 00:00 {
		filename "pxelinux.0";
	}
}
